### ISSUE TITLE
Scaling the spline based latent trait densities in EM algorithm

### ISSUE THREAD

**Issue by oguzhanogreden** [oguzhanogreden/mirt#1]
This is a follow up on the issue I created in [the original mirt repo](https://github.com/philchalmers/mirt/issues/130).

I created [a report](http://www.oguzhanogreden.com/mirt/index.html) of what comes closest to a reproducible and worked out example.

In this report I identify the main problem as follows: "While discussing the use of Ramsay curves in IRT context, Woods and Thissen (2006) introduce a method to scale the spline based densities." which this implementation currently ignores.

However, it's not clear to me how to perform the linear interpolation-extrapolation part.

**Comment by oguzhanogreden** [comment]
Revisiting the first resource I read on this matter, I realized I have been overlooking a presentation of technical details: Chapter 4 of Handbook of Item Response Theory (page 67), subsection "Scale Identifcation When g(θ) Is Estimated".

I still have trouble seeing the problem precisely. I'll turn to that.

**Comment by oguzhanogreden** [comment]
The problem is a bit more clearer now, so is my question.

I understand the standardization and the following interpolation/extrapolation. Now the question is where to insert this.

My current idea is to standardize, then interpolate/extrapolate the vector [here](https://github.com/oguzhanogreden/mirt/blob/dcirt/R/EMstep.utils.R#L249).

**Comment by oguzhanogreden** [comment]
Interpolation and extrapolation is implemented [here](https://github.com/oguzhanogreden/mirt/blob/dcirt-std/R/interp_exterp.R). It plays into estimation [here](https://github.com/oguzhanogreden/mirt/blob/dcirt-std/R/EMstep.utils.R#L254).

However, this did not solve the problem. In fact, it broke the estimation. Not even the shape of the density is recovered anymore. Perhaps this approach and `mirt` estimation logic is not immediately compatible.

**Comment by philchalmers** [comment]
I'm having some trouble following this, particularly the part where the density is re-normed manually somehow. The flow seems fine: compute the E-step given the new g(theta) term implied by some B-spline, compute the usual M-step on the item parameters, and finally compute the M-step for the g(theta) term to obtain an improved density. But, I don't quite follow the implementation. Where was equation (4.11) supposed to be located? I don't see a use of `exp()` or `integrate()` anywhere in the full git diff. 

Is it possible for you to explain how this is supposed to work for just one iteration given some expectation table? I just don't quite see how this implementation combines to obtain the g(theta) term. Once that is available the estimation portion should be quite simple and straightforward.

**Comment by philchalmers** [comment]
Also, do you have a working script that I can test your forked version with? That way I'll be able to walk through parts of the code that I'm unsure of. Thanks.

**Comment by philchalmers** [comment]
Isn't [this line](https://github.com/oguzhanogreden/mirt/blob/395597526422b655e196ed17ae930aa0aeb04e97/R/interp_exterp.R#L17) supposed to reflect the standardisation of the expected frequency, `nq`? This looks like you just standardise the range of quadrature, which would be fixed throughout estimation. That might explain why your shapes never change.

**Comment by oguzhanogreden** [comment]
I implemented **Davidian** curve (DC) IRT, not **Ramsay** curve (RC) IRT. _Equation (4.11)_ is relevant only for the latter. Perhaps it was too early for abbreviations :)

Davidian curves related functions are in [davidRian package](https://github.com/oguzhanogreden/davidRian). The separate package was simply for ease while developing.

In light of these, walking through an E table is not necessary I think. Let me know if you'd still like to see it.

---

Let me also clarify the branches in this repo: `dcirt` and `dcirt-std`. The difference is that `dcirt` **does not** implement the scale identification step described in the literature. Please note that the `dcirt` branch was used to obtain results in the [demonstration](http://www.oguzhanogreden.com/mirt/index.html) I posted.

I added a sample script [here](https://github.com/oguzhanogreden/mirt/blob/gh-pages/R/exampleScript.R). You can use this to check the procedure. (You can use the same for `dcirt-std` branch, but see below...)

---

I decided to go for the `dcirt-std` branch since the shapes of the densities were recovered, but not as precisely as it should have been. Please refer to the [demonstration](http://www.oguzhanogreden.com/mirt/index.html) for this point.

You are absolutely right, I am standardizing only the quadrature points. This was intentional since standardizing the expectation count doesn't make sense to me. If I `scale(nq)`, I'll end up with negative values expected frequencies. Realizing this, I thought "I must be misunderstanding this." and went on with standardizing only the quadrature points.

If we both think they talk about standardization of both... Do I then replace all negative values with zero?

**Comment by philchalmers** [comment]
Thanks for the reply.

On Sun, Feb 25, 2018 at 10:40 AM, Oğuzhan Öğreden <notifications@github.com>
wrote:

> I implemented *Davidian* curve (DC) IRT, not *Ramsay* curve (RC) IRT. *Equation
> (4.11)* is relevant only for the latter. Perhaps it was too early for
> abbreviations :)
>
> Davidian curves related functions are in davidRian package
> <https://github.com/oguzhanogreden/davidRian>. The separate package was
> simply for ease while developing.
>
> In light of these, walking through an E table is not necessary I think.
> Let me know if you'd still like to see it.
>

Thanks for clarifying; I see what you're trying now. My mistake mixing up
terminologies.


> ------------------------------
>
> Let me also clarify the branches in this repo: dcirt and dcirt-std. The
> difference is that dcirt *does not* implement the scale identification
> step described in the literature. Please note that the dcirt branch was
> used to obtain results in the demonstration
> <http://www.oguzhanogreden.com/mirt/index.html> I posted.
>
> I added a sample script here
> <https://github.com/oguzhanogreden/mirt/blob/gh-pages/R/exampleScript.R>.
> You can use this to check the procedure. (You can use the same for
> dcirt-std branch, but see below...)
>

Great, thank you. This will be helpful.


> ------------------------------
>
> I decided to go for the dcirt-std branch since the shapes of the
> densities were recovered, but not as precisely as it should have been.
> Please refer to the demonstration
> <http://www.oguzhanogreden.com/mirt/index.html> for this point.
>
> You are absolutely right, I am standardizing only the quadrature points.
> This was intentional since standardizing the expectation count doesn't make
> sense to me. If I scale(nq), I'll end up with negative values expected
> frequencies. Realizing this, I thought "I must be misunderstanding this."
> and went on with standardizing only the quadrature points.
>
> If we both think they talk about standardization of both... Do I then
> replace all negative values with zero?
>
I think this is simply an artefact of the setup and should be expected
based on the standardization. From Monro and Cai's (2015) brief description
of this method: "First, revise the E-step by using the current
characterization of g(ujh) to find the conditional expectation of u. As
before, fill in the E-step tables for each item. Second, estimate the
proportion of respondents at each quadrature point, denoted N (x q ), by
summing across all E-step tables. Following Woods and Thissen (2006), at
this point, the scale is identified by standardizing N (x q ) to have a
mean of 0 and variance of 1. Finally, in the M-step, update the RC
parameters."

So it sounds like the N(theta) terms have negative components from the
get-go, and so this extrapolation-interpolation process is just used to
rescale the terms to match theta before actually performing the M-step
(it's slightly unclear why this is required to me, but I haven't looked
into it much).

The only thing I don't particularly like about this EM approach is that
it's not clear what the complete data-gradient term should look like under
the rescaling, which means that computing the ACOV is rather difficult.

**Comment by oguzhanogreden** [comment]
>(it's slightly unclear why this is required to me, but I haven't looked into it much).

I don't understand this either. Just now I came across something in [Woods, **_2004_**](http://dx.doi.org/10.1037/1082-989X.11.3.253) (on **_RC_**-IRT). Figure 1 contains a plot of the B-spline and it's integral. **This is not a density.** They write:
>Finally, the bottom right panel shows the Ramsay curve, computed by exponentiating W (at each quadrature point) and renormalizing _**so the result is a proper density**_. The scale of the latent variable is identified by setting its mean and variance to 0 and 1, respectively (see Woods, 2004, for details).

So they first make it a density, then scale it. Alright.

---

On the other hand, we read in [Woods & Lin, **_2009_**, (p. 105)](http://journals.sagepub.com/doi/abs/10.1177/0146621608319512) (on **_DC_**-IRT) that the Davidian curve automatically integrates to 1. **This is already a proper density** with the current parameterization. Further, I think it identifies the scale. The only difference is that the identification is not by fixing the mean and the standard deviation.

Imagine two cases under my implementation:
1. The estimated latent density is identical to standard normal distribution (which is possible), only expressed as DC. 
2. The estimated latent density is given by this density:
 `ddc(x, 0, 1, c(77.32, 78.51, 76.33, 77.16))`

Why would I _need_ to do anything extra?

---

Coming back to my [tests](http://www.oguzhanogreden.com/mirt/index.html)... There I used two specific distributions, which were taken from Woods and Lin (2009). For these, they write (on page 107): "[...] distributions have mean = 0 and variance = 1".

So we're talking of a bimodal distribution such that it has a variance of 1. And their implementation estimates this well. On the other hand, a bimodal distribution may as well a variance of 2.18, the above given one has this actually. If we generated data on a true density with a variance larger than 1, perhaps my implementation could perform the same, if not better. If the true variance was 5, both could fail.

I do not have access to their code, unfortunately. I think I will go ahead and try if my implementation will pass an internally referenced density recovery test.

---

PS: Ignoring the negative expected frequencies, the log-likelihood becomes positive due to [this line](https://github.com/oguzhanogreden/mirt/blob/dcirt-std/R/EMstep.utils.R#L269). So I'll not go that way.

**Comment by philchalmers** [comment]
I see, this intra-extrapolation is being used to set the (otherwise
intractable) scale to [0,1], so this step is required in both methods. I
think the key though lies in the last line of the descriptions: "After
standardization and translation back to the original quadrature, the
histogram is
renormalized, and used for the M-step." The renormalized part doesn't
appear in these computations. E..g., playing around with your three
functions in interp_exterp.R:

```
set.seed(1)
qp <- -6:6
nq <- sample(1:100, 13)
(N <- sum(nq))

> 635

out <- standardizeQuadrature(qp, nq)
sum(out[,2]) # must equal N

> 32496.63
```

If the column really is to be used in the M-step then it has to sum to N.
So I think they mean to apply something like this to re-norm it:

```
# renorm
renorm <- function(x, N) x / sum(x) * N
new_nq <- renorm(out[,2], N)
sum(new_nq)

> 635
```

I'm not really sure why all these values are expressed as std_nq though in
the 2016 chapter rather than nq as your done, where std_nq <- scale(nq).
That doesn't seem to work with the extrapolation method (produces NaN in
most places). Might not hurt to ask either Thissen or Woods about this
formula and whether it's indeed correct. From what I can see, the asterisk
are just distracting as these refer to the original expected frequency
terms.





Phil

**Comment by oguzhanogreden** [comment]
Thanks, I appreciate this a lot!

One final thing. Perhaps this has an obvious answer that I'm missing. Precisely what is the property Davidian curves are lacking? They,
- always integrate to 1 (= will integrate well)
- never have any mass outside about [-7.5, 7.5] (= scale identification).

Best,
Oguzhan

**Comment by philchalmers** [comment]
Right, but proper integration to one is not the problem here. By that reasoning you could do something wild like

```r
den <- dnorm(Theta, mean=rnorm(1), sd = lnorm(1))
```
and try to use this density function during estimation (which without rescaling, is basically what is occurring). Under your properties:

- It always integrates to 1, regardless of the input parameters
- Has basically no mass outside [-10,10]

But the metric of the pdf is not constrained during estimation, so the model is not identified. One would need to constrain this center (0) and scale (1) constraint in most IRT models to ensure that the density for the Theta terms converges to the same location each time.

**Comment by oguzhanogreden** [comment]
It has to be the _simplest_ thing, of course...

I have been using `scale()` to standardize `funky_densities(seq(-6, 6, .1))`, while neither mean of funky_densities() was 0 nor SD was 1. I use the mean and SD of and my densities match the published ones.

I'll repeat the tests.

**Comment by oguzhanogreden** [comment]
I've repeated the tests, no success... Heading to #6 .
