### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by oguzhanogreden** [oguzhanogreden/mirt#10]
UI issues have already come up [here](https://github.com/philchalmers/mirt/issues/130#issuecomment-360167063).

I'd be willing to implement an idea like what is suggested over in the original fork. I have the time for this as well. I only need to know that we agree on an idea and go for it.

**Comment by philchalmers** [comment]
This type of refactoring seems reasonable at this point in time. I was thinking of supporting at least 4 types for a new `trait.type` argument: 'Guassian' (default), 'empiricalhist', 'empiricalhistWoods' (for the former method, but using Wood's standardized quadrature approach), and 'Davidian'. Naturally, all but the first would be supported for multidimensional models.

**Comment by philchalmers** [comment]
Come to think of it, this might be a bit to much to put on your end. I'll refactor the relevant code on the master branch and we can re-base from there instead.

**Comment by oguzhanogreden** [comment]
Thanks. Feel free to assign me to tasks if explaining them turns out to be an economical alternative to implementing them.

**Comment by philchalmers** [comment]
I've refactored the code in the master branch to reflect a new `dentype` input, with documentation in the `mirt` help file. Currently only `dentype = 'Gaussian'` and `dentype = 'empiricalhist'` are supported, though syncing this now should be easy (note that the inputs to `dentype` are checked in the `mirt:::makeopts()` function). 

I'm thinking something like `dentype = 'Davidian-6'` to implement the previous Davidian inputs `dcIRT = T` and  `dcIRT_nphi = 6`, which could be accomplished by a simple string-split operation. This form is something I've been thinking about when I find time to add mixture IRT models into the package, so having this already implemented for DC curves would be great to keep with future consistency.

**Comment by philchalmers** [comment]
This might be a little easier at this point if I had push access to this repo; otherwise, I could make a fork and send a pull request. Let me know which approach you're most comfortable with.
