### ISSUE TITLE
Merge changes

### ISSUE THREAD

**Issue by philchalmers** [oguzhanogreden/mirt#11]
I'll try to keep track of any major internal changes here so that you know what I've been modifying. 

- `standardizeQuadrature()` has been made slightly more robust when `n[1] - n[2]` is numerically 0
- `standardizeQuadrature()` returns a vector instead of a matrix
- the DC optimizer is always `nlminb()` because it is more stable than L-BFGS-B with bounds (this likely explains the normal curves that appeared in the simulation, because L-BFGS-B was just terminating at the starting values), and the optimizer M-step inputs were simplified 
- added a test to the `test/` folder to check if/when this function could break through all the internal changes (much to add still)

There's still much left to do to make this compatible, but this is a good start. I was particularly puzzled about adding the extro-interpolation to the empirical histogram method to ensure the scale was always [0,1], as Woods claimed was a good strategy in the paper

    Woods, C. M. DIF Testing With an Empirical- Histogram Approximation of the Latent Density for Each Group Applied Measurement in Education, 2011, 24, 256-279

because the log-likelihood simply jumps around all the time in the single-group case. Feel free to check this out if you find it interesting [here](https://github.com/oguzhanogreden/mirt/blob/d124e561e2f6f84ea056fd43bf73a66ce0167be3/R/utils.R#L428).

**Comment by philchalmers** [comment]
Also, I don't really understand [this line](https://github.com/oguzhanogreden/mirt/blob/d124e561e2f6f84ea056fd43bf73a66ce0167be3/R/interp_exterp.R#L19): `qp_m <- sum(qp) / sum(nq)`. 

Given that `qp` is always constructed to be symmetric around 0, it will the numerator is always 0, and therefore `qp_m` is always equal to 0. How does this standardize the mean then?

**Comment by philchalmers** [comment]
This line in Woods' 2011 paper mentioned above resonates with me: 

> To identify the scale in EH-DIF-2, the R-group EH is standardized in every
> E-step: The difference between the mean and every Ni(θq) is divided by the
> SD.

where Ni(θq) is the expected count in the E-table. Again, this seems to allude to something being changed in the frequencies themselves, not just the quadrature. Likely explains why the empirical histogram approach with this standardization is not functioning correctly too.

**Comment by philchalmers** [comment]
Update: applying the ".001 if it became smaller than .0000001" adjustment seems to fix the empirical histogram (it's at least no longer wildly jumping around), and may influence the stability of the DC curves as well.

**Comment by philchalmers** [comment]
Spoke too soon, this still demonstrates major problems basically across the board. I'm still suspicious of the extrapolation/interpolation portion (one day this will be determined officially.....). Here's an example of how this is failing:

```
dat <- key2binary(SAT12,
    key = c(1,4,5,2,3,1,2,1,3,1,2,4,2,1,5,3,4,4,1,4,3,3,4,1,3,5,1,3,1,5,4,5))
mod <- mirt(dat, 1, dentype = 'empiricalhist', quadpts=121)
```

**Comment by oguzhanogreden** [comment]
- `qp_m <-` line indeed lacked the term you added.
-  The text from the 2011 paper matches also most of her texts. Then again, the sentence you quote is followed by: "This linear transformation alters neither the number of quadrature points nor the equal spacing between them. However, values of the quadrature points do change, [...]" If she's referring to the frequencies, the transformation she describes would not change the quadrature points. I can start an email thread with her to settle this.

Thanks for the commits!

**Comment by oguzhanogreden** [comment]
Your EH implementation normalizes the scale by following Bock & Aitkin's `sum(nq) = 1` constraint, right? Do you think it's possible that the software Woods is building on doesn't do this at all? They seem to write about the proposed method as if it could replace the constraint altogether.

I ended up thinking they may have a different implementation of EH also because of a comment in the 2009 paper of Woods, p. 108:

> For the EHM, the quadrature points were started at these locations but altered during estimation by an adaptive algorithm in BILOG-MG.

Let me link this back to the failure here: The failure is due to the presence of a perfect response pattern. Both of the methods pick on this and assigns density to the rightmost quadrature point (you can check 35th cycle). Then, the interpolation and extrapolation picks up on this and amplifies, as expected. It doesn't fail if you remove them.

The adaptive algorithm could be ensuring that rightmost point doesn't have a density higher than the one to its left. In this case, extrapolation wouldn't lead to this kind of failure. I can imagine this becoming a "How to picture the density on infinity?" problem but one can come up with all sorts of algorithmic solutions for it.

**Comment by oguzhanogreden** [comment]
I merged these into the master of this repo. Leaving this open for empiricalwoods discussions.

I have less of an overview of the package than you. So I prefer going test-driven here for warnings, input checks etc. Feel free to populate the tests file further, either by complete test statements or comments.

**Comment by philchalmers** [comment]
> Your EH implementation normalizes the scale by following Bock & Aitkin's sum(nq) = 1 constraint, right? Do you think it's possible that the software Woods is building on doesn't do this at all? They seem to write about the proposed method as if it could replace the constraint altogether.

Correct. The software Woods uses does this as well, but fixes the scaling of the thetas; likely by just changing the quadrature to match the first part of Woods' approach but without the extrapolation/interpolation part (my speculation....this isn't documented anywhere).  

> Let me link this back to the failure here: The failure is due to the presence of a perfect response pattern. Both of the methods pick on this and assigns density to the rightmost quadrature point (you can check 35th cycle). Then, the interpolation and extrapolation picks up on this and amplifies, as expected. It doesn't fail if you remove them.

Interesting, this limitation doesn't exist in B&A's discussion of the topic, but you're probably right with this implementation that's extrapolating. I'm fine with whatever solution you want here, such as just setting these extreme response pattern densities to 0 and using the N_2/N_N3 and N_(Q-1)/N_(Q-2) instead when this occurs for the extrapolation portion.

**Comment by philchalmers** [comment]
If this extrapolation problem always occurs at the extreme ends where these frequencies become unstable, why not just always use the following:

```r
for (i in 1:length(qp)) {
        if (qp[i] <= min_stdqp) {
            res[i] <- extrapolateWoods(qp[i], min_stdqp, nq[2], nq[3], delta, "left")
        } else if (max_stdqp <= qp[i]) {
            res[i] <- extrapolateWoods(qp[i], max_stdqp, nq[length(nq)-2], nq[length(nq)-1], delta, "right")
        } else {
            std_ind <- max(which(qp[i] > std_qp))
            res[i] <- interpolateWoods(qp[i], std_qp[std_ind], nq[std_ind], nq[std_ind+1], delta)
        }
    }
```

It seems unusual to extrapolate based on the expected frequencies right at the end of the theta distribution when this is the most unstable/unreliable location. In fact, selecting the expected frequency *closest* to the theta locations where extrapolation is needed might be that much more stable. It's extrapolation after all, so there's likely no one "best" way to do this.

**Comment by philchalmers** [comment]
I've played around with this a little more, and I can't determine a reasonably good strategy to overcome the problem in all cases. The best approach may be just to remove these extreme response cases when using the Woods extrapolation method (or equivalently, giving these a `survey.weight` of 0). Though I'm not a fan of modifying users data without warning, I can add a `technical` argument flag to do this removal when required, and we can simply make a note in the documentation that the extrapolation technique is prone to issues when all/none response patterns are present.

**Comment by oguzhanogreden** [comment]
Have you observed this problem during the Davidian curve estimation when you played around? I'd expect that this wouldn't occur there.

**Comment by philchalmers** [comment]
Indeed, this looks like it was an artefact from other tests. I think the row-removal strategy is only required for the empirical histogram method. I'll adjust this to be less aggressive for the Davidian implementation.

**Comment by philchalmers** [comment]
I've reverted this survey.weight approach to the more natural philosophy of leaving the user data unmodified. A note in the documentation now states that the `zeroExtreme` technical option *may* be required for `dentype = 'EWH'`, but this will not be used by default for consistency with the rest of the package.
