### ISSUE TITLE
Optimization bounds

### ISSUE THREAD

**Issue by philchalmers** [oguzhanogreden/mirt#15]
https://github.com/oguzhanogreden/mirt/blob/553402f7ade7e5070b178dec32bec22e6b8261d6/R/EMstep.utils.R#L238

I don't really understand the logic of these boundaries. Given that the parameterization is essentially being passed to a bunch of cos() and sin() functions, should these be bounded somewhere closer to [-pi, pi]?

**Comment by philchalmers** [comment]
Both of those papers seem to state that: -\pi/2 < \phi_t < \pi/2 under the sign reparameterization for half the unit sphere. So in order to obtain all possible values for both cos() and sign we should make the bounds between +- pi. Otherwise, we get multiple locations of the expected values, which could confuse the optimizer: `cos(1.5); cos(1.5 + 2*pi)`

**Comment by philchalmers** [comment]
I tested this out using the bounds both these authors recommended, [-pi/2, pi/2], and changed the starting values of the `phi` vector to 0 (a bunch of warnings resulted from `dcurver`, but that's fine). The shape looks to be recovered well still. I'd recommend changing the starting values and bounds for this optimization problem to match and to ensure identification.

**Comment by oguzhanogreden** [comment]
I'll digest the comment about extending the bounds.

I'd expect that 0 starting values to be a bad idea due to [this line](https://github.com/oguzhanogreden/dcurver/blob/master/src/estFuncs.cpp#L32). It's not clear from Woods & Lin how to go about `1/tan(phi)` here. I had played around before and found out when I wrote 1 in this line, results matched the numerical approximation. 

Today I realized it doesn't... So I think that the gradient is actually wrong when the phis are 0 in the CRAN version. I submitted a patch today where the gradient function will return 0 for `phi=0`.  Github master branch reflects this.

(I'll take a detailed look at this tomorrow, it's the end of the workday here.)

**Comment by philchalmers** [comment]
The same `1/tan(phi)` derivative issue occurs at the values `-3pi`, `-pi`, `0`, `pi`, `3pi`, `5pi`, and so on, which is another reason why the parameter space is bounded. It's more likely these derivative locations should return `NaN` to indicate that they are not well defined mathematically (divide by 0 issue).

**Comment by oguzhanogreden** [comment]
I couldn't wrap my mind around your comments on the bounds. [-pi, pi] would make a unit sphere, not a half unit sphere, right?

And about the link between multiple locations and bounds:.. You're pointing to this, right? `y = cos(x1) = cos(x2)` for `x1 != x2` in these bounds. Though, the optimizer works on `f(\theta; x)` and it's not clear to me if this equality is reflected directly there. Also, this is possible for `cos(x)` in `(-pi/2, pi/2]` too. In the end, I don't feel quite comfortable departing from the text here.

---
I thought returning 0 would be one way to prevent optimizers from breaking down, while also minimizing the influence of this issue for the next step of the optimizer. Now that I think again, `dcurver::dc_grad` needs to be wrapped for use anyway. So I'll revert it to `NaN`.

**Comment by philchalmers** [comment]
> I couldn't wrap my mind around your comments on the bounds. [-pi, pi] would make a unit sphere, not a half unit sphere, right?

Correct. This was my initial interpretation of the problem, though are correct that in-text these authors recommend focusing on the half unit sphere [-pi/2, pi/2]. Their recommendation seems reasonable to me as it would necessarily avoid the indeterminacy.

**Comment by philchalmers** [comment]
Okay, this is going to seem a little odd, but bare with me. I suggest we change the `nlminb()` optimization space to be completely unbounded, and let the optimizer converge to wherever it thinks is easiest. Then, following convergence, manually reparameterize the estimates (within the M-step) for the phi vector by noting that these are all unique up to the additive constant c*pi, where c is an integer number. That way, we can manually select a vector of phi estimates that necessarily fall within the [-pi/2, pi] bounds while not having to deal with the bounded parameter space in the optimizer.  

Here's an example with the above code, though with the transformation done post MLE convergence. 

```r
phi_bound <- function(phi, bound = c(-pi/2, pi/2)){
    while(TRUE){
        if(phi < bound[1L]) phi <- phi + pi
        if(phi >= bound[2L]) phi <- phi - pi
        if(phi > bound[1L] && phi <= bound[2L]) break
    }
    phi
}

cfs0 <- cfs1 <- coef(res_bm1)$GroupPars
for(i in 1:6)
    cfs1[i + 2] <- phi_bound(cfs0[i + 2])
cfs0  ## 
cfs1

cfs0 <- cfs1 <- coef(res_bm2)$GroupPars
for(i in 1:6)
    cfs1[i + 2] <- phi_bound(cfs0[i + 2])
cfs0
cfs1

cfs0 <- cfs1 <- coef(res_bm3)$GroupPars
for(i in 1:6)
    cfs1[i + 2] <- phi_bound(cfs0[i + 2])
cfs0
cfs1
```

You'll notice that all `cfs1` objects give the same parameter set, which satisfies the required identification constraint. Neat, right?

**Comment by philchalmers** [comment]
Okay, I've provided a reasonably clever solution to this problem that effectively solves this issue. The optimiser is now allowed to be unbounded and to rest on whatever phi vector is convenient, even if this means the solution is not within the desired boundary. Then, I translate the values that are outside the bound according to a +- pi rule, and multiply these translated terms by -1 and 1 until the equivalent complete-data log-likelihood solution is obtained. 

This approach means that the boundary issue I discussed above is no longer present, and no further optimisation is required (other than computing the Davidian log-likelihood function a few times more until the equivalent signs of the translated vector are found). Note that this boundary issue stabilizes very quickly anyway after the first few EM iterations, where the stability of the M-step will start converging to this [-pi/2, pi] location anyway.

**Comment by philchalmers** [comment]
Stochastic component removed in the last commit, which definitively closes this issue. The entire grid of possible signs is now searched, if necessary, and terminated the instant the correct sign orientation is located. We likely could solve this sign search analytically, but given that this basically only needs to executed one-two times in the EM cycle I don't see the need. Feel from to comment if you are unsure of what I did to fix this issue.
