### ISSUE TITLE
New `parnames` input

### ISSUE THREAD

**Issue by philchalmers** [oguzhanogreden/mirt#3]
Just a placeholder until later when a pull request will occur. Rebasing from the original mater branch will provide a better means to obtain the `parnames` for each item, which you noted was confusing and more difficult to track throughout. See [here](https://github.com/philchalmers/mirt/issues/137) for a recent issue highlighting the implications.

**Comment by oguzhanogreden** [comment]
Thanks, I was dreading the idea of finding a walk-around to make the PR neat.
