### ISSUE TITLE
Find mean and SD using the E-table

### ISSUE THREAD

**Issue by oguzhanogreden** [oguzhanogreden/mirt#5]
**What is needed?**

During the standardization of E-table as discussed in issue #1 at length, we need the mean and standard deviation of the density represented by the table.

**What is the current state?**

Just to get an idea about the numerical value for some testing, quadrature points are now sampled to obtain an estimate of mean and the standard deviation. See [here](https://github.com/oguzhanogreden/mirt/commit/d8f22988ae3f9aa4503e1f88d897307cfef6a395#r27930304).

**Comment by oguzhanogreden** [comment]
[Here](http://www.oguzhanogreden.com/mirt/e-table.Rdata) is an example extracted from mirt for quickly testing ideas.

Relevant code snippet from [`EMstep.utils.R`](https://github.com/oguzhanogreden/mirt/blob/dcirt-std/R/EMstep.utils.R#L234):
```
tmp_samp <- sample(gTheta[[1]], 10000, T, rr)
obs_m <- mean(tmp_samp)
obs_sd <- sd(tmp_samp)

gTheta_std <- (gTheta[[1]] - obs_m) / obs_sd
std_qp <- standardizeQuadrature(gTheta[[1]], gTheta_std, rr)
rr_std <- std_qp[,2] / sum(std_qp[,2]) * sum(rr)```

**Comment by philchalmers** [comment]
I think you're overthinking this a little. Consider from your `.Rdata` file:

```
fTheta <- gTheta[[1]] * rr
obs_m <- sum(fTheta) / sum(rr)
obs_sd <- sqrt(sum(rr * (gTheta[[1]] - obs_m)^2) / sum(rr))
```

You'd need to do this anyway because `rr` contains fractions, but to convince yourself it works consider what happens if all the values in `rr` were integers (i.e., it's just like repeating terms). 

```
# compare with integers
rr2 <- sample(10:20, length(rr), TRUE)
fTheta <- gTheta[[1]] * rr2
(obs_m <- sum(fTheta) / sum(rr2))
sqrt(sum(rr2 * (gTheta[[1]] - obs_m)^2) / sum(rr2))

Theta2 <- do.call(c, sapply(1:121, function(x) rep(gTheta[[1]][x], rr2[x])))
mean(Theta2)
sd(Theta2) * sum(rr2) / (sum(rr2)-1)
```

**Comment by philchalmers** [comment]
The standardisation above for the `Theta` terms seems basically solved now, resulting in what Woods represents as `\theta^*`, but I'm still very confused as to what Woods is referring to when she says the E-table itself is "standardized", the `N^*` components. In the current implementation the expected frequencies are being used (`N`), so it doesn't quite match, and apparently these too were "standardized" by subtracting some mean and SD (what, exactly, is not clear, though given the transformation applied to `Theta` it likely is the same transformation to match the mean/SD shift). 

But, unless this re-norming adds some constant to the transformed values to avoid negative frequencies (occurring whether one uses `scale()` or the `obs_m` or `obs_sd`), I just don't understand how it could work. E.g., the following works in that the frequencies are re-normed and look appropriate, but details like this do not appear in any text that I know of. 

```r
load("~/Downloads/e-table.Rdata")
fTheta <- gTheta[[1]] * rr
obs_m <- sum(fTheta) / sum(rr)
obs_sd <- sqrt(sum(rr * (gTheta[[1]] - obs_m)^2) / sum(rr))
gTheta_std <- (gTheta[[1]] - obs_m) / obs_sd

std_rr <- (rr - obs_m) / obs_sd # # apply same transformation to expected frequencies
std_qp <- standardizeQuadrature(gTheta[[1]], gTheta_std, std_rr)
std_qp[,2] <- std_qp[,2] - min(std_qp[,2]) # make all values positive
rr_std <- std_qp[,2] / sum(std_qp[,2]) * sum(rr)

plot(rr_std)
```

**Comment by oguzhanogreden** [comment]
I see. I'm fine with going the way you suggest here. I'll fix it and focus on trying to get estimation going again.

---

I agree that this doesn't match with what is written out there. Though I'm inclined to think that the writing wasn't particularly clear but pointed towards this. Two bits of information to support this:

(1) I asked someone who used this in a paper of theirs, they confirmed that this is it. I'll not write a name here to prevent indexing but I can share the email with you. (2) Woods was kind enough to send her dissertation to me. Here is the "Identification of the Scale" subsection:

>Typically, the scale for IRT models is identified by fixing the mean and standard
deviation of the normal population distribution at 0 and 1, respectively. It is desirable to
identify the scale for RC-IRT models in the same way; however, this is not straightforward
because the mean and standard deviation of the curve are not its parameters, or simple
functions of the parameters. Therefore, instead of directly standardizing the population distribution, the histogram of expected frequencies is standardized in the E-step of the EM
algorithm. Then, given that the M-step fits only the pseudo-data for the E-step, the resulting
g(θq) is also standardized. 

>In the E-step, the expected frequencies at the quadrature points are computed as a
histogram, which then may be standardized: **_Each quadrature point minus the mean is divided
by the standard deviation._** This linear transformation alters neither the number of quadrature
points nor the equal spacing between them. However, the particular values of the quadrature
points change, which is problematic because they need to match the quadrature points used
for the item “data”. So, the standardized histogram is translated back to the original
quadrature using linear interpolation and extrapolation.

And moves on to the mathematical description of inter-/extrapolation.

**Comment by philchalmers** [comment]
Thanks, that was kind of Woods to share her dissertation. Given the above text though, it's still not clear to me with regards to the 'renorming' step for the intro-extrapolated E-table (I feel like I've read this exact same paragraph in at least 10 of Woods' papers, each avoiding the same negative value frequency topic). 

Applying the same `(# - obs_m) / obs_sd` to both the quadrature and the expected frequencies themselves is fine, and I understand that logic, but then how does one re-norm the expected frequencies after this centering/rescaling. The approach I did above works, but is not the only way to do it. For example, if `std_rr` is the extrapolated vector of frequencies containing both positive and negative numbers, then we could also use 

`exp(std_rr) / sum(exp(std_rr)) * N`

to accomplish the same goal, and indeed this would avoid having exactly one element necessarily == 0. To me, it's just unusual that this step is rarely (if ever) stated in-text in the published articles. Hopefully you see something like this in the dissertation.

**Comment by philchalmers** [comment]
I'm still mulling over the meaning of these extrapolated-interpolated frequency terms containing negative values, though maybe like my initial suspicion in #1 this is simply an artefact of the method and is of no real consequence. Applying either of my approaches (the adjustment by adding the minimum to all values, or using the exp() form) do not seem appropriate they again re-scale the values so as to not match the original quadrature locations. 

So, perhaps these negative values in the tails of the extra-interpolated frequencies are okay in the M-step since they just represent pseudo data anyway, and still preserve the general shape of the complete data log-likelihood function. I would try this way first with the scaling adjustment + re-norming described in this issue to see if this matches with the published results, and if this works then I suspect it is the correct approach.

**Comment by oguzhanogreden** [comment]
I think one thing that she wrote _slightly_ different in her dissertation is that she specifically talks about standardizing "each quadrature point". 

You wrote,
> Applying the same (# - obs_m) / obs_sd to both the quadrature and the expected frequencies themselves is fine, and I understand that logic,

I don't think we should apply this to expected frequencies. When they wrote `N^*`, they simply meant "This is the expected frequency vector corresponding to `q^*`. They did not mean that the `N^*` was standardized `N`. I can them using this notation for clarity of the following point: "We will then extra-interpolate `N^*` to obtain `N` which corresponds to `q`."

This unfortunately remains a guess... One just grows to love open source :) Anyway, I consider this enough of a confirmation. Using the E-table file above:

```
fTheta <- gTheta[[1]] * rr
obs_m <- sum(fTheta) / sum(rr)
obs_sd <- sqrt(sum(rr * (gTheta[[1]] - obs_m)^2) / sum(rr))

gTheta_std <- (gTheta[[1]] - obs_m) / obs_sd
std_qp <- standardizeQuadrature(gTheta[[1]], gTheta_std, rr) # This now only works on quad. pts.

std_m <- sum(std_qp[,1]) / sum(std_qp[,2]) # ~ 0
std_sd <- sqrt(sum(std_qp[,2] * (std_qp[,1] - std_m) ^ 2) / sum(std_qp[,2])) # ~ 1
```

---

I'll spend today creating an isolated example for estimation of the Davidian curve, which follows this and fails at the moment. I'll post my findings here.

**Comment by philchalmers** [comment]
I see what you're saying, and yes this sounds reasonable. What an awkward use of notation..... Hopefully this matches the implementation after it's added. Good luck.

**Comment by oguzhanogreden** [comment]
Since we agree on this. I'll deliver the bad news [here](https://github.com/oguzhanogreden/davidRian/issues/2).
