### ISSUE TITLE
Remove davidRian package dependency

### ISSUE THREAD

**Issue by oguzhanogreden** [oguzhanogreden/mirt#7]
It's probably better to not depend on the [davidRian](https://github.com/oguzhanogreden/davidRian) repo I created.

I tried copying the `.cpp` files into `mirt`. When I tried to compile after that, I get an error about a C+11 feature I used. When I tell the compiler to use C+11 standards, it fails due to mirt code.

There are also some style differences between my C++ code and the `mirt` code. Most obvious is that I use Rcpp attributes (e.g. `[[Rcpp::Export]]`) and the `mirt` code does the export to R manually.

**Comment by philchalmers** [comment]
Failing this, I don't see why `davidRian` can't be submitted to CRAN, and then passed as an IMPORT package to mirt. I think the functions serve an interesting purpose in isolation, and I'm not completely confident that the two C++ releases can be easily merged into the same package (CRAN has strict policies at times, and this could be one of them).

**Comment by oguzhanogreden** [comment]
I hadn't considered the CRAN route simply because I wasn't able to judge what would be needed here.

This is fine by me. I'll prepare it for CRAN.
